server:
  port: 8090

spring:
  application:
    name: finance_tool
  datasource:
    url: jdbc:mysql://host:port/ruoyi-vue-pro?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

email:
  from: ${EMAIL_FROM}
  password: ${EMAIL_PASSWORD}
  defaultTo: ${EMAIL_DEFAULTTO}
  host: ${EMAIL_HOST}
  protocol: ${EMAIL_PROTOCOL}
  smtpAuth: ${EMAIL_SMTPAUTH}
  debug: ${EMAIL_DEBUG}
  content: ${EMAIL_CONTENT}